-- Region pack it: authority entities, their domain aliases and email rules.
-- Idempotent: safe to run again. Generated from rules.json "authorities"; only
-- senders whose domain is known go here, everything else is classified by judgement.
